global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/api/payments/metrics'
    static_configs:
      - targets: ['payment-service:8081']


  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  