openapi: 3.0.0
info:
  description: "The application is divided into microservice, for each microservice\
    \ there is a RESTful API created, this is the organizer API"
  title: Organizer API
  version: 1.0.0
servers:
- url: http://localhost:8080/v1
paths:
  /organizers:
    post:
      operationId: organizersPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_organizers_post_request'
        required: true
      responses:
        "201":
          description: Organizer created successfully
      summary: Adds a new organizer
      x-eov-operation-handler: controllers/DefaultController
  /organizers/{id}:
    patch:
      operationId: organizersIdPATCH
      parameters:
      - description: ID of the organizer to modify
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_organizers_post_request'
        required: true
      responses:
        "201":
          description: Organizer modified successfully
      summary: Modifies the info of an existing organizer
      x-eov-operation-handler: controllers/DefaultController
    
    delete:
      operationId: organizersIdDelete
      parameters:
      - description: ID of the organizer to modify
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "201":
          description: Organizer deleted successfully
      summary: Deletes the info of an existing organizer
      x-eov-operation-handler: controllers/DefaultController
    
    get:
      operationId: organizersIdGET
      parameters:
      - description: ID of the organizer to get
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "201":
          description: Organizer retrived successfully
      summary: gets the info of an existing organizer
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Event:
      example:
        images:
        - https://example.com/event-image.jpg
        - https://example.com/event-image.jpg
        event_type: Concert
        artist: Helena Hauff
        event_location: Arena
        ticket_types:
        - price: 500.0
          type: VIP
        - price: 500.0
          type: VIP
        event_address: ElSawy Culture Wheel
        description: "Expect pulsating beats, minimal lighting, and a stripped-back\
          \ industrial setting that will transport you straight to the roots of Berlin’\
          s legendary rave culture."
        dates:
        - 2025-07-10T19:30:00Z
        - 2025-07-10T19:30:00Z
        city_location: Cairo
        capacity: 200
      properties:
        event_type:
          example: Concert
          type: string
        event_location:
          example: Arena
          type: string
        event_address:
          example: ElSawy Culture Wheel
          type: string
        artist:
          example: Helena Hauff
          type: string
        description:
          example: "Expect pulsating beats, minimal lighting, and a stripped-back\
            \ industrial setting that will transport you straight to the roots of\
            \ Berlin’s legendary rave culture."
          type: string
        dates:
          items:
            example: 2025-07-10T19:30:00Z
            format: date-time
            type: string
          type: array
        city_location:
          example: Cairo
          type: string
        capacity:
          example: 200
          type: integer
        ticket_types:
          items:
            $ref: '#/components/schemas/Event_ticket_types_inner'
          type: array
        images:
          items:
            example: https://example.com/event-image.jpg
            format: uri
            type: string
          type: array
      type: object
    EventUpdate:
      example:
        price: 250
      properties:
        price:
          example: 250
          type: integer
      type: object
    EventCapacity:
      example:
        capacity: 100
      properties:
        capacity:
          example: 100
          type: integer
      type: object
    EventHistory:
      properties:
        type:
          example: Concert
          type: string
        artist:
          example: Helena Hauff
          type: string
        description:
          example: "Expect pulsating beats, minimal lighting, and a stripped-back\
            \ industrial setting that will transport you straight to the roots of\
            \ Berlin’s legendary rave culture."
          type: string
        dates:
          items:
            format: date-time
            type: string
          type: array
        location:
          example: Cairo
          type: string
        capacity:
          example: 200
          type: integer
        price:
          example: 500
          type: integer
      type: object
    _organizers_post_request:
      properties:
        organization_name:
          example: Cairo's organization for concerts
          type: string
        industry_type:
          example: Concerts
          type: string
        primary_contact_name:
          example: Shahd Hosam
          type: string
        email:
          example: shahd@gmail.com
          format: email
          type: string
        password:
          example: detectiveConan
          format: password
          type: string
        username:
          example: shahdhoss
          type: string
      type: object
    _organizers_payment_info__id__post_request:
      properties:
        organizer_id:
          example: org_12345
          type: string
        credit_card_number:
          type: integer
          example: null
        expiration_date:
          format: date
          type: string
          example: null
        payment_methods:
          example:
          - Credit Card
          - Cash
          items:
            type: string
          type: array
        currency:
          example: EGP
          type: string
      type: object
    _organizers_payment_info__id__post_201_response:
      example:
        message: Payment details added successfully.
      properties:
        message:
          example: Payment details added successfully.
          type: string
      type: object
    _organizers_payment_info__id__post_400_response:
      example:
        error: Invalid bank account number format.
      properties:
        error:
          example: Invalid bank account number format.
          type: string
      type: object
    _organizers_payment_info__id__post_500_response:
      example:
        error: An unexpected error occurred.
      properties:
        error:
          example: An unexpected error occurred.
          type: string
      type: object
    Event_ticket_types_inner:
      example:
        price: 500.0
        type: VIP
      properties:
        type:
          example: VIP
          type: string
        price:
          example: 500.0
          format: float
          type: number
      type: object
