openapi: 3.0.0
info:
  title: Ticket Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /tickets:
    post:
      operationId: ticketsPOST
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketInput'
      responses:
        '200':
          description: Ticket created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
      x-eov-operation-handler: controllers/DefaultController

  /tickets/{id}:
    get:
      summary: Get a ticket by ID
      operationId: ticketsIdGET
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ticket retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
      x-eov-operation-handler: controllers/DefaultController

    patch:
      summary: Update a ticket by ID
      operationId: ticketsIdPATCH
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketInput'
      responses:
        '200':
          description: Ticket updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
      x-eov-operation-handler: controllers/DefaultController
    delete:
      summary: Delete a ticket by ID
      operationId: ticketsIdDELETE
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Ticket deleted
      x-eov-operation-handler: controllers/DefaultController

components:
  schemas:
    TicketInput:
      type: object
      properties:
        user_id:
          type: integer
        seat_number:
          type: string
        status:
          type: string
          enum: [booked, canceled, pending]
        price:
          type: number
      required:
        - user_id
        - seat_number
        - status
        - price

    Ticket:
      allOf:
        - $ref: '#/components/schemas/TicketInput'
        - type: object
          properties:
            id:
              type: integer
