openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: User Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "shahd@gmail.com"
                password:
                  type: string
                  format: password
                  example: "detectiveConan"
                username:
                  type: string
                  example: "shahdhoss"
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input data

  /auth/login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "shahd@gmail.com"
                password:
                  type: string
                  format: password
                  example: "newpassword"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        '401':
          description: Invalid credentials
