openapi: 3.0.0
info:
  title: Events API
  version: 1.0.0
  description: The application is divided into microservice, for each microservice there is a RESTful API created, this is the organizer API

servers: 
  - url: http://localhost:8080/v1 

paths:
  /events:
    post:
      summary: Add a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully

  /events/{id}:
    get:
      summary: Get an event by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the event to retrieve
      responses:
        '200':
          description: Gets an event using event id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    delete:
      summary: Delete an event by id
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Deletes an event using event id


    patch:
      summary: Partially update an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the event to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventUpdate'
      responses:
        '204':
          description: Event updated successfully
        '404':
          description: Event not found

components:
  schemas:
    Event:
      type: object
      properties:
        event_type:
          type: string
          example: "Concert"
        event_location:
          type: string
          example: "Arena"
        event_address:
          type: string
          example: "ElSawy Culture Wheel"
        artist:
          type: string
          example: "Helena Hauff"
        description:
          type: string
          example: "Expect pulsating beats, minimal lighting, and a stripped-back industrial setting that will transport you straight to the roots of Berlin’s legendary rave culture."
        dates:
          type: array
          items:
            type: string
            format: date-time
            example: "2025-07-10T19:30:00Z"
        city_location:
          type: string
          example: "Cairo"
        capacity:
          type: integer
          example: 200
        ticket_types:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: "VIP"
              price:
                type: number
                format: float
                example: 500.00
        images:
          type: array
          items:
            type: string
            format: uri
            example: "https://example.com/event-image.jpg"

    EventUpdate:
      type: object
      properties:
        price:
          type: integer
          example: 250
    EventHistory :
      type: object
      properties:
        type:
          type: string
          example: "Concert"
        artist:
          type: string
          example: "Helena Hauff"
        description:
          type: string
          example: "Expect pulsating beats, minimal lighting, and a stripped-back industrial setting that will transport you straight to the roots of Berlin’s legendary rave culture."
        dates:
          type: array
          items:
            type: string
            format: date-time
        location:
          type: string
          example: "Cairo"
        capacity:
          type: integer
          example: 200
        price:
          type: integer
          example: 500
