openapi: 3.0.0
info:
  title: Organizer API
  version: 1.0.0
  description: The application is divided into microservice, for each microservice there is a RESTful API created, this is the organizer API

servers: 
  - url: http://localhost:8080/v1

paths:
  /organizers:
    post:
      summary: Adds a new organizer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_name:
                  type: string
                  example: "Cairo's organization for concerts"
                industry_type:
                  type: string
                  example: "Concerts"
                primary_contact_name:
                  type: string
                  example: "Shahd Hosam"
                email:
                  type: string
                  format: email
                  example: "shahd@gmail.com"
                password:
                  type: string
                  format: password
                  example: "detectiveConan"
                username:
                  type: string
                  example: "shahdhoss"
      responses:
        '201':
          description: Organizer created successfully
  
  /organizers/{id}:  
    patch:
      summary: Modifies the info of an existing organizer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the organizer to modify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_name:
                  type: string
                  example: "Cairo's organization for concerts"
                industry_type:
                  type: string
                  example: "Concerts"
                primary_contact_name:
                  type: string
                  example: "Shahd Hosam"
                email:
                  type: string
                  format: email
                  example: "shahd@gmail.com"
                password:
                  type: string
                  format: password
                  example: "detectiveConan"
                username:
                  type: string
                  example: "shahdhoss"
      responses:
        '201':
          description: Organizer modified successfully
  /organizers/payment_info/{id}:
    post:
      summary: Add payment details for an organizer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the event to reserve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organizer_id:
                  type: string
                  example: "org_12345"
                credit_card_number:
                  type: integer
                  example: 
                expiration_date:
                  type: string
                  format: date
                  example:
                payment_methods:
                  type: array
                  items:
                    type: string
                  example: ["Credit Card", "Cash"]
                currency:
                  type: string
                  example: "EGP"
      responses:
        '201':
          description: Payment info added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Payment details added successfully."
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid bank account number format."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred."
