openapi: 3.0.0
info:
  title: Payment API
  version: 1.0.0
  description: The application is divided into microservice, for each microservice there is a RESTful API created, this is the ticket holding API

paths:
  /payments:
    post:
      summary: Initiate a new payment for a reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservation_id:
                  type: integer
                  description: The ID of the reservation
                amount:
                  type: number
                  description: The amount to be paid
                payment_method:
                  type: string
                  description: The payment method (e.g., "credit_card", "paypal")
      responses:
        '201':
          description: Payment initiated successfully
        '400':
          description: Invalid request data
        '500':
          description: Payment processing failed

  /deposit/{id}:
    post:
      summary: Confirms the payment of reserved ticket/tickets using reservation ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the reservation
      responses:
        '201':
          description: Payment done successfully
        '500':
          description: Payment failed
        '404':
          description: Payment not found

  /refund/{id}:
    post:
      summary: Refund the payment (full or partial) using reservation ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the reservation to refund
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: The amount to be refunded (if not provided, full refund is processed)
      responses:
        '204':
          description: Reservation payment refunded successfully
        '404':
          description: Payment not found
        '400':
          description: Invalid refund amount

  /payments/{id}/status:
    get:
      summary: Get the status of a payment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the payment
      responses:
        '200':
          description: Payment status retrieved successfully
        '404':
          description: Payment not found

  /payments/history:
    get:
      summary: Get a list of past transactions
      parameters:
        - name: customer_id
          in: query
          required: true
          schema:
            type: integer
          description: The ID of the customer whose payment history is requested
      responses:
        '200':
          description: Payment history retrieved successfully
        '404':
          description: No transactions found

  /payment-methods:
    get:
      summary: Retrieve available payment methods
      responses:
        '200':
          description: List of available payment methods

    post:
      summary: Add a new payment method for a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: The type of payment method (e.g., "credit_card", "paypal")
                details:
                  type: object
                  description: Encrypted payment details
      responses:
        '201':
          description: Payment method added successfully
        '400':
          description: Invalid payment method details

  /payment-methods/{method_id}:
    delete:
      summary: Remove a saved payment method for a customer
      parameters:
        - name: method_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the payment method to be deleted
      responses:
        '204':
          description: Payment method deleted successfully
        '404':
          description: Payment method not found

