openapi: 3.0.0
info:
  title: Ticket holding API
  version: 1.0.0
  description: The application is divided into microservice, for each microservice there is a RESTful API created, this is the ticket holding API

paths:
  /hold/{id}:
    post:
      summary: Hold a ticket or a number of tickets using event id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the event to reserve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: The number of tickets to be booked
                seat_type:
                  type: string
                  enum: ["VIP", "Front Row", "Balcony", "General Admission"]
                  description: Type of seat for the reservation
                seat_number:
                  type: string
                  description: Seat number of the reservations

              required:
                - seat_type
                - seat_number
                - quantity
      responses:
        '201':
          description: Reservation done successfully
        '500':
          description: Reservation failed
        '404':
          description: Event not found

    patch:
      summary: Update a user's ticket holding
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the reservation to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Updated number of tickets
                seat_type:
                  type: string
                  enum: ["VIP", "Front Row", "Balcony", "General Admission"]
                  description: Updated seat type
                seat_number:
                  type: string
                  description: Updated seat number
              required:
                - quantity
      responses:
        '200':
          description: Reservation updated successfully
        '404':
          description: Reservation not found
        '500':
          description: Internal server error



    delete:
      summary: Delete the holding of a ticket after it being fully reserved
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Deletes an event reservation using event id


          example: 500
